apiVersion: v1
kind: Pod
metadata:
  name: third
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  containers:
  - name: third
    image: busybox:latest
    command: ["/bin/sh", "-c", "tail -f /dev/null"]