apiVersion: v1
kind: Pod
metadata:
  name: fifth
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  containers:
  - name: fifth
    image: busybox:latest
    command: ["/bin/sh", "-c", "tail -f /dev/null"]