apiVersion: v1
kind: Pod
metadata:
  name: post-sync
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  containers:
  - name: post-sync
    image: busybox:latest
    command: ["/bin/sh", "-c", "tail -f /dev/null"]