apiVersion: v1
kind: Pod
metadata:
  name: first
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  containers:
  - name: first
    image: busybox:latest
    command: ["/bin/sh", "-c", "tail -f /dev/null"]